const mongoose = require('mongoose');
const home = require('../Controllers/User');
const { post } = require('../Routes/User');
const objectId = mongoose.Schema.Types.ObjectId;
const userSchema = new mongoose.Schema({
    first_name:{
        type:String,
        trim:true,
        required:true
    },
    last_name:{
        type:String,
        trim:true,
        required:true
    },
    email:{
        type:String,
        trim:true,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    picture:{
        type:String,
        default:'/profile.png'
    },
    coverpicture:{
        type:String,
        default:'/cover.jpg'
    },
    gender:{
        type:String,
        required:true
    },
    bday:{
        type:Number,
        required:true
    },
    bmonth:{
        type:String,
        required:true
    },
    byear:{
        type:Number,
        required:true
    },
    verified:{
        type:Boolean,
        default:false
    },
    friends:{
        type:[
            {
                type:objectId,
                ref:'User'
            }
        ]
    },
    following:{
        type:[{
            type:objectId,
            ref:'User'
        }]
    },
    followers:{
        type:[{
            type:objectId,
            ref:'User'
        }]
    },
    company:{
        type:Boolean,
        default:false
    },
    search:[
        {
            type:objectId,
            ref:'User'
        }
    ],
    details:{
        bio:{
            type:String,
            default:''
        },
        job:{
            type:String
        },
        workplace:{
            type:String
        },
        highschool:{
            type:String
        },
        university:{
            type:String
        },
        city:{
            type:String
        },
        hometown:{
            type:String
        },
        instagram:{
            type:String
        },
        x:{
            type:String
        },
    },
    savedposts:[{
        post:{
            type:objectId,
            ref:'Post'
        },
        savedAt:{
            type:Date,
            default:new Date()
        }
    }]
},{
    timestamps:true
});

module.exports = mongoose.model('User',userSchema);
